config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  get "cards/index"
  get "cards/show"
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"
  resources :cards, only: [:index, :show]
  resources :colors, only: [:index]
  resources :keywords, only: [:index]
  resources :card_types, only: [:index]
  get "about", to: "pages#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    has_many :cards_colors, dependent: :destroy
    has_many :colors, through: :cards_colors

    has_many :cards_keywords, dependent: :destroy
    has_many :keywords, through: :cards_keywords

    has_many :cards_card_types, dependent: :destroy
    has_many :card_types, through: :cards_card_types

    validates :card_name, presence: true, uniqueness: true
end

app/models/card_type.rb
class CardType < ApplicationRecord
    has_many :cards_card_types, dependent: :destroy
    has_many :cards, through: :cards_card_types

    validates :card_type, presence: true, uniqueness: true
end

app/models/cards_card_type.rb
class CardsCardType < ApplicationRecord
  belongs_to :card
  belongs_to :card_type

  # No instance of double instants shall occur unless playing Storm.
  validates :card_id, uniqueness: { scope: :card_type_id }
end

app/models/cards_color.rb
class CardsColor < ApplicationRecord
  belongs_to :card
  belongs_to :color

  # For a given card ID, each color ID must be unique.
  validates :card_id, uniqueness: { scope: :color_id }
end

app/models/cards_keyword.rb
class CardsKeyword < ApplicationRecord
  belongs_to :card
  belongs_to :keyword

  # Each keyword should only appear once per card.
  # Multiple instances of lifelink on the same creature are redundant. 
  validates :card_id, uniqueness: { scope: :keyword_id }
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :cards_colors, dependent: :destroy
    has_many :cards, through: :cards_colors

    validates :color, presence: true, uniqueness: true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
    has_many :cards_keywords, dependent: :destroy
    has_many :cards, through: :cards_keywords

    validates :keyword, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/card_types_controller.rb
class CardTypesController < ApplicationController
  def index
    @cardtypes = CardType.order(:card_type)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @colors = Color.order(:color)
    @card_types = CardType.order(:card_type)
    @keywords = Keyword.order(:keyword)
    @cards = Card.includes(:colors, :card_types, :keywords)

    if params[:query].present?
      @cards = Card.where("card_name LIKE ?", "%#{params[:query].downcase}%")
    end

    if params[:color_id].present?
        @cards = @cards.joins(:colors).where(colors: { id: params[:color_id] })
    end

    if params[:card_type_id].present?
        @cards = @cards.joins(:card_types).where(card_types: { id: params[:card_type_id] })
    end

    if params[:keyword_id].present?
        @cards = @cards.joins(:keywords).where(keywords: { id: params[:keyword_id] })
    end

    @cards = @cards.page(params[:page]).per(20)
    # else
    #   @cards = Card.includes(:colors, :keywords, :card_types).limit(50)
    # end
  end

  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
    @colors = Color.order(:color)
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
    @keywords = Keyword.order(:keyword)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/card_types/index.html.erb
<h1>All Card Types</h1>
<ul>
  <% @cardtypes.each do |cardtype| %>
    <li><%= cardtype.card_type.capitalize %></li>
  <% end %>
</ul>

app/views/cards/_card_filters_nav.html.erb
<nav class="card-collection-nav">
  <strong>Explore:</strong>
  <%= link_to "All Cards", cards_path %> |
  <%= link_to "All Colors", colors_path %> |
  <%= link_to "All Keywords", keywords_path %> |
  <%= link_to "All Card Types", card_types_path %>
</nav>

app/views/cards/index.html.erb
<h1>Card Browser</h1>

<%= render "card_filters_nav" %>

<%= form_with url: cards_path, method: :get do %>
    <p>
        <%= label_tag :query, "Search by Name:" %>
        <%= text_field_tag :query, params[:query] %>
    </p>

    <p>
        <%= label_tag :color_id, "Filter by Color:" %>
        <%= select_tag :color_id,
            options_from_collection_for_select(@colors, :id, :color, params[:color_id]),
            include_blank: true
        %>
    </p>

    <p>
        <%= label_tag :card_type_id, "Filter by Type:" %>
        <%= select_tag :card_type_id,
            options_from_collection_for_select(@card_types, :id, :card_type, params[:card_type_id]),
            include_blank: true
        %>
    </p>

    <p>
        <%= label_tag :keyword_id, "Filter by Keyword:" %>
        <%= select_tag :keyword_id,
            options_from_collection_for_select(@keywords, :id, :keyword, params[:keyword_id]),
            include_blank: true
        %>
    </p>

    <%= submit_tag "Search" %>
    <%= link_to "Clear", cards_path, class: "button", style: "margin-left: 10px;" %>
<% end %>

<ul>
  <% @cards.each do |card| %>
    <li>
      <%= link_to card.card_name.titleize, card_path(card) %>
      <% if card.mana_cost.present? %> - <%= card.mana_cost %><% end %>
    </li>
  <% end %>
</ul>

<%= paginate @cards %>

<% if @cards.empty? %>
  <p>No cards found :(</p>
<% end %>

app/views/cards/show.html.erb
<h1><%= @card.card_name %></h1>

<p><strong>Mana Cost:</strong> <%= @card.mana_cost %></p>
<p><strong>Card Text:</strong> <%= @card.description %></p>

<% # https://www.rubyguides.com/2018/10/ruby-map-method/ %>
<% if @card.colors.any? %>
  <p><strong>Colors:</strong> <%= @card.colors.map(&:color).join(", ") %></p>
<% end %>

<% if @card.keywords.any? %>
  <p><strong>Keywords:</strong> <%= @card.keywords.map(&:keyword).join(", ") %></p>
<% end %>

<% if @card.card_types.any? %>
  <p><strong>Card Type:</strong> <%= @card.card_types.map(&:card_type).join(", ") %></p>
<% end %>

<%= link_to "Back to Card Browser", cards_path %>

app/views/colors/index.html.erb
<h1>All Colors</h1>
<ul>
  <% @colors.each do |color| %>
    <li><%= color.color.capitalize %></li>
  <% end %>
</ul>

app/views/keywords/index.html.erb
<h1>All Keywords</h1>
<ul>
  <% @keywords.each do |keyword| %>
    <li><%= keyword.keyword.capitalize %></li>
  <% end %>
</ul>

<%= link_to "Back to Card Browser", cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Intro" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1><u>About This Project</u></h1>
<p>This is a Rails project that loads and displays Magic: The Gathering cards using data from MTGJSON.</p>
<p>Data includes card names, mana cost, card text, card types, keywords, and color identity.</p>

<h2>About the Data</h2>
The data used in this project has been gathered from <a href="https://mtgjson.com/">MTGJSON</a>.
<p>The cards are from this dataset: <a href="https://mtgjson.com/data-models/card/card-atomic/">Atomic Cards</a></p>
<p>The keywords are from this dataset: <a href="https://mtgjson.com/data-models/keywords/">Keywords</a></p>
<p>And the card types are from this dataset: <a href="https://mtgjson.com/data-models/card-types/">Types</a></p>
Each of these datasets sports their own table, and a joiner table exists between each dataset and the Atomic Cards dataset.<br>

This is because, in Magic: the Gathering, many cards can have many colors, abilities, and card types.
So many-to-many relationships are a natural fit for this project.<br>
You never know what you're going to find on a card. That's what keeps the game fun and exciting.

<h3>Entity Relationship Diagram</h3>
<%= image_tag "ERD.jpg", alt: "Entity Relationship Diagram" %>

app/views/pages/home.html.erb
<h1>Welcome to MTG Cards DB</h1>
<p>This site contains most Magic: the Gathering cards, browse through them, or check out the About page!</p>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Browse Cards", cards_path %></li>
    <li><%= link_to "About", about_path %></li>
  </ul>
</nav>